CREATE TABLE IF NOT EXISTS USUARIO (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone INT NOT NULL,
    avatar VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS RELATION (
    follower_id VARCHAR(255) NOT NULL,
    followed_id VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    PRIMARY KEY (follower_id, followed_id),
    FOREIGN KEY (follower_id) REFERENCES USUARIO (id),
    FOREIGN KEY (followed_id) REFERENCES USUARIO (id)
);

CREATE TABLE IF NOT EXISTS GRUPO (
    id VARCHAR(255) PRIMARY KEY,
    admin_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description INT NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES USUARIO (id)
);

ALTER TABLE USUARIO group_id VARCHAR(255) NOT NULL,
ADD CONSTRAINT id_grupo_fk
FOREIGN KEY(group_id) REFERENCES GRUPO (id);

CREATE TABLE IF NOT EXISTS PAGINA (
    id VARCHAR(255) PRIMARY KEY,
    admin_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description INT NOT NULL,
    banner INT NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES USUARIO (id)
);

CREATE TABLE IF NOT EXISTS CURTIDAS_PAGINA (
    user_id VARCHAR(255) NOT NULL,
    page_id VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, page_id),
    FOREIGN KEY (user_id) REFERENCES USUARIO (id),
    FOREIGN KEY (page_id) REFERENCES PAGINA (id)
);


CREATE TABLE IF NOT EXISTS EVENTO (
    id VARCHAR(255) PRIMARY KEY,
    admin_id VARCHAR(255) NOT NULL,
    page_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description INT NOT NULL,
    date INT NOT NULL,
    local VARCHAR(255) NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES USUARIO (id),
    FOREIGN KEY (page_id) REFERENCES PAGINA (id)
);

CREATE TABLE IF NOT EXISTS POST (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description INT NOT NULL,
    image VARCHAR(255) NOT NULL,
    event_id VARCHAR(255),
    group_id VARCHAR(255),
    page_id VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES USUARIO (id),
    FOREIGN KEY (event_id) REFERENCES EVENTO (id),
    FOREIGN KEY (group_id) REFERENCES GRUPO (id),
    FOREIGN KEY (page_id) REFERENCES PAGINA (id)
);

CREATE TABLE IF NOT EXISTS CURTIDAS_POST (
    post_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    PRIMARY KEY (follower_id, followed_id),
    FOREIGN KEY (post_id) REFERENCES POST (id),
    FOREIGN KEY (user_id) REFERENCES USUARIO (id)
);
