CREATE TABLE IF NOT EXISTS USUARIOS (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone INT NOT NULL,
    avatar VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS RELATIONS (
    follower_id VARCHAR(255),
    followed_id VARCHAR(255),
    date VARCHAR(255) NOT NULL,
    PRIMARY KEY (follower_id, followed_id),
    FOREIGN KEY (follower_id) REFERENCES FULLSTACK_USUARIOS (id),
    FOREIGN KEY (followed_id) REFERENCES FULLSTACK_USUARIOS (id)
);
